Tap verilog
leonardt/silica pull request #13
Opened 2018-10-18 00:17 UTC by rdaly525

2018-10-18 15:27 UTC, leonardt requested changes
Awesome, looks good, thanks! Minor comment on adding fault to requirements.txt, is that necessary? It's already in the `setup.py`, so installation should be managed there.

2018-10-18 15:27 UTC, leonardt commented on requirements.txt
> +git+git://github.com/leonardt/fault.git#egg=fault
Is this required? `fault` installation should be handled in `setup.py`

2018-10-18 15:37 UTC, rdaly525 commented
@leonardt, I reverted the requirements.txt

2018-10-19 02:09 UTC, leonardt approved these changes
Looks good, thanks! At some point I may run this file through a processor to make it 4 space tabs. Not a blocking issue, but to keep the codebase consistent, it's nice to have every file follow the same style. (I know I'm an offender of inserting 4 space tabs in the 2 space tabs code base of coreir). But I'll defer the formatting to a tool which should make it easy to change (mainly just want to avoid merge conflicts from whitespace changes).

2018-10-19 02:09 UTC, merged

2018-10-19 02:12 UTC, leonardt commented
https://github.com/leonardt/silica/commit/741a5a21dfa8ba145d80674b161e354ae666c537

It's been done, probably a good idea to get those changes ASAP if you plan to modify the file.